name: Build and Deploy to S3

on:
  push:
    branches:
      - master  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Set the Node.js version, adjust as needed

    # Install dependencies and build backend
    - name: Install Backend dependencies
      run: |
        cd backend
        npm install

    - name: Build Backend
      run: |
        cd backend
        npm run build  # Adjust if your build script is different

    # Install dependencies and build frontend
    - name: Install Frontend dependencies
      run: |
        cd 
        npm install

    - name: Build Frontend
      run: |
        cd example-app-nodejs-backend-react-frontend
        npm run build

    # Configure AWS credentials using OIDC (IAM Role)
    - name: Configure AWS Credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::851725217291:role/front1  # The ARN of the role to assume
        aws-region: ${{ secrets.AWS_REGION }}

    # Deploy to S3 using AWS CLI
    - name: Deploy to S3 using AWS CLI
      run: |
        aws s3 sync ./frontend/build/ s3://cloudtera123/ --delete
